# Generated by Django 5.2.7 on 2025-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KoboSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(db_index=True, help_text='Kobo submission UUID (_uuid)', max_length=100, unique=True)),
                ('form_uid', models.CharField(db_index=True, help_text='Kobo form/asset UID', max_length=100)),
                ('data', models.JSONField(help_text='Complete submission data from Kobo')),
                ('date_submitted', models.DateTimeField(db_index=True, help_text='Submission timestamp from Kobo')),
                ('date_synced', models.DateTimeField(auto_now_add=True, help_text='When this record was created in Django')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'verbose_name': 'Kobo Submission',
                'verbose_name_plural': 'Kobo Submissions',
                'ordering': ['-date_submitted'],
                'indexes': [models.Index(fields=['-date_submitted'], name='api_kobosub_date_su_5848db_idx'), models.Index(fields=['form_uid', '-date_submitted'], name='api_kobosub_form_ui_f201fa_idx')],
            },
        ),
    ]
